version: '3'
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
      DISK_SIZE: "20G"
      USERNAME: "admin"
      PASSWORD: "Admin@12345"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - "3389:3389"
      - "8006:8006"
    restart: unless-stopped
